Ruby Enumerables, Project #2: Request for Code review
wickathou/ruby-enumerables pull request #1
Opened 2019-10-29 02:18 UTC by wickathou

Features a custom implementation of the Enumerable methods:
+ each
+ each_with_index
+ select
+ all?
+ any?
+ none?
+ count
+ map
+ inject

2019-11-07 10:03 UTC, maelfosso requested changes
# Changes required

Hello @wickathou 

For a first try you did a really awesome job :clap: 
However there are some changes to do. Please read the comments left below.
Also, please fix all the **sticklers** errors.

Kindly make the changes and submit a new code review request.
Thanks

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

2019-11-07 10:03 UTC, maelfosso commented on module.rb
> +  end
See the differences between the two last ouput
```ruby
irb(main):020:0> array
=> [6, 7, 6, 4, 4, 2, 5, 1, 2, 5, 2, 3, 7, 6, 0, 3, 7, 0, 3, 1, 3, 4, 5, 3, 7, 8, 8, 5, 5, 5, 8, 1, 1, 0, 6, 4, 3, 7, 7, 4, 0, 0, 0, 1, 2, 7, 0, 8, 2, 8, 5, 1, 3, 5, 7, 6, 2, 1, 6, 2, 1, 5, 2, 5, 4, 0, 3, 4, 0, 2, 3, 6, 7, 0, 3, 5, 0, 6, 6, 3, 8, 3, 4, 2, 7, 7, 8, 7, 7, 5, 8, 1, 8, 1, 5, 2, 2, 1, 0, 5]
irb(main):021:0> my_each_output = ''
=> ""
irb(main):022:0> each_output = ''
=> ""
irb(main):023:0> block = proc { |num, idx| each_output += "Num: #{num}, idx: #{idx}\n" }
=> #<Proc:0x000055a97f377278@(irb):23>
irb(main):024:0> array.each_with_index(&block)
=> [6, 7, 6, 4, 4, 2, 5, 1, 2, 5, 2, 3, 7, 6, 0, 3, 7, 0, 3, 1, 3, 4, 5, 3, 7, 8, 8, 5, 5, 5, 8, 1, 1, 0, 6, 4, 3, 7, 7, 4, 0, 0, 0, 1, 2, 7, 0, 8, 2, 8, 5, 1, 3, 5, 7, 6, 2, 1, 6, 2, 1, 5, 2, 5, 4, 0, 3, 4, 0, 2, 3, 6, 7, 0, 3, 5, 0, 6, 6, 3, 8, 3, 4, 2, 7, 7, 8, 7, 7, 5, 8, 1, 8, 1, 5, 2, 2, 1, 0, 5]
irb(main):025:0> block = proc { |num, idx| my_each_output += "Num: #{num}, idx: #{idx}\n" }
=> #<Proc:0x000055a97f3117e8@(irb):25>
irb(main):028:0> array.my_each_with_index(&block)
=> nil
irb(main):029:0> each_output
=> "Num: 6, idx: 0\nNum: 7, idx: 1\nNum: 6, idx: 2\nNum: 4, idx: 3\nNum: 4, idx: 4\nNum: 2, idx: 5\nNum: 5, idx: 6\nNum: 1, idx: 7\nNum: 2, idx: 8\nNum: 5, idx: 9\nNum: 2, idx: 10\nNum: 3, idx: 11\nNum: 7, idx: 12\nNum: 6, idx: 13\nNum: 0, idx: 14\nNum: 3, idx: 15\nNum: 7, idx: 16\nNum: 0, idx: 17\nNum: 3, idx: 18\nNum: 1, idx: 19\nNum: 3, idx: 20\nNum: 4, idx: 21\nNum: 5, idx: 22\nNum: 3, idx: 23\nNum: 7, idx: 24\nNum: 8, idx: 25\nNum: 8, idx: 26\nNum: 5, idx: 27\nNum: 5, idx: 28\nNum: 5, idx: 29\nNum: 8, idx: 30\nNum: 1, idx: 31\nNum: 1, idx: 32\nNum: 0, idx: 33\nNum: 6, idx: 34\nNum: 4, idx: 35\nNum: 3, idx: 36\nNum: 7, idx: 37\nNum: 7, idx: 38\nNum: 4, idx: 39\nNum: 0, idx: 40\nNum: 0, idx: 41\nNum: 0, idx: 42\nNum: 1, idx: 43\nNum: 2, idx: 44\nNum: 7, idx: 45\nNum: 0, idx: 46\nNum: 8, idx: 47\nNum: 2, idx: 48\nNum: 8, idx: 49\nNum: 5, idx: 50\nNum: 1, idx: 51\nNum: 3, idx: 52\nNum: 5, idx: 53\nNum: 7, idx: 54\nNum: 6, idx: 55\nNum: 2, idx: 56\nNum: 1, idx: 57\nNum: 6, idx: 58\nNum: 2, idx: 59\nNum: 1, idx: 60\nNum: 5, idx: 61\nNum: 2, idx: 62\nNum: 5, idx: 63\nNum: 4, idx: 64\nNum: 0, idx: 65\nNum: 3, idx: 66\nNum: 4, idx: 67\nNum: 0, idx: 68\nNum: 2, idx: 69\nNum: 3, idx: 70\nNum: 6, idx: 71\nNum: 7, idx: 72\nNum: 0, idx: 73\nNum: 3, idx: 74\nNum: 5, idx: 75\nNum: 0, idx: 76\nNum: 6, idx: 77\nNum: 6, idx: 78\nNum: 3, idx: 79\nNum: 8, idx: 80\nNum: 3, idx: 81\nNum: 4, idx: 82\nNum: 2, idx: 83\nNum: 7, idx: 84\nNum: 7, idx: 85\nNum: 8, idx: 86\nNum: 7, idx: 87\nNum: 7, idx: 88\nNum: 5, idx: 89\nNum: 8, idx: 90\nNum: 1, idx: 91\nNum: 8, idx: 92\nNum: 1, idx: 93\nNum: 5, idx: 94\nNum: 2, idx: 95\nNum: 2, idx: 96\nNum: 1, idx: 97\nNum: 0, idx: 98\nNum: 5, idx: 99\n"
irb(main):030:0> my_each_output
=> "Num: 0, idx: \nNum: 1, idx: \nNum: 2, idx: \nNum: 3, idx: \nNum: 4, idx: \nNum: 5, idx: \nNum: 6, idx: \nNum: 7, idx: \nNum: 8, idx: \nNum: 9, idx: \nNum: 10, idx: \nNum: 11, idx: \nNum: 12, idx: \nNum: 13, idx: \nNum: 14, idx: \nNum: 15, idx: \nNum: 16, idx: \nNum: 17, idx: \nNum: 18, idx: \nNum: 19, idx: \nNum: 20, idx: \nNum: 21, idx: \nNum: 22, idx: \nNum: 23, idx: \nNum: 24, idx: \nNum: 25, idx: \nNum: 26, idx: \nNum: 27, idx: \nNum: 28, idx: \nNum: 29, idx: \nNum: 30, idx: \nNum: 31, idx: \nNum: 32, idx: \nNum: 33, idx: \nNum: 34, idx: \nNum: 35, idx: \nNum: 36, idx: \nNum: 37, idx: \nNum: 38, idx: \nNum: 39, idx: \nNum: 40, idx: \nNum: 41, idx: \nNum: 42, idx: \nNum: 43, idx: \nNum: 44, idx: \nNum: 45, idx: \nNum: 46, idx: \nNum: 47, idx: \nNum: 48, idx: \nNum: 49, idx: \nNum: 50, idx: \nNum: 51, idx: \nNum: 52, idx: \nNum: 53, idx: \nNum: 54, idx: \nNum: 55, idx: \nNum: 56, idx: \nNum: 57, idx: \nNum: 58, idx: \nNum: 59, idx: \nNum: 60, idx: \nNum: 61, idx: \nNum: 62, idx: \nNum: 63, idx: \nNum: 64, idx: \nNum: 65, idx: \nNum: 66, idx: \nNum: 67, idx: \nNum: 68, idx: \nNum: 69, idx: \nNum: 70, idx: \nNum: 71, idx: \nNum: 72, idx: \nNum: 73, idx: \nNum: 74, idx: \nNum: 75, idx: \nNum: 76, idx: \nNum: 77, idx: \nNum: 78, idx: \nNum: 79, idx: \nNum: 80, idx: \nNum: 81, idx: \nNum: 82, idx: \nNum: 83, idx: \nNum: 84, idx: \nNum: 85, idx: \nNum: 86, idx: \nNum: 87, idx: \nNum: 88, idx: \nNum: 89, idx: \nNum: 90, idx: \nNum: 91, idx: \nNum: 92, idx: \nNum: 93, idx: \nNum: 94, idx: \nNum: 95, idx: \nNum: 96, idx: \nNum: 97, idx: \nNum: 98, idx: \nNum: 99, idx: \n"
irb(main):031:0> 
```

2019-11-07 10:03 UTC, maelfosso commented on module.rb
> +  end
See the differences between the two outputs
```ruby
irb(main):033:0> block = proc { |num| num < 4 }
=> #<Proc:0x000055a97f3bc620@(irb):33>
irb(main):034:0> array
=> [6, 7, 6, 4, 4, 2, 5, 1, 2, 5, 2, 3, 7, 6, 0, 3, 7, 0, 3, 1, 3, 4, 5, 3, 7, 8, 8, 5, 5, 5, 8, 1, 1, 0, 6, 4, 3, 7, 7, 4, 0, 0, 0, 1, 2, 7, 0, 8, 2, 8, 5, 1, 3, 5, 7, 6, 2, 1, 6, 2, 1, 5, 2, 5, 4, 0, 3, 4, 0, 2, 3, 6, 7, 0, 3, 5, 0, 6, 6, 3, 8, 3, 4, 2, 7, 7, 8, 7, 7, 5, 8, 1, 8, 1, 5, 2, 2, 1, 0, 5]
irb(main):035:0> array.select(&block)
=> [2, 1, 2, 2, 3, 0, 3, 0, 3, 1, 3, 3, 1, 1, 0, 3, 0, 0, 0, 1, 2, 0, 2, 1, 3, 2, 1, 2, 1, 2, 0, 3, 0, 2, 3, 0, 3, 0, 3, 3, 2, 1, 1, 2, 2, 1, 0]
irb(main):036:0> array.my_select(&block)
=> [2]
```

2019-11-07 10:03 UTC, maelfosso commented on module.rb
> +  end
```ruby
irb(main):039:0> false_array = [1, false, 'hi', []]
=> [1, false, "hi", []]
irb(main):040:0> false_array.all?
=> false
irb(main):041:0> false_array.my_all?
=> true
```

2019-11-07 10:03 UTC, maelfosso commented on module.rb
> +  end
```ruby
irb(main):047:0> words = %w[dog door rod blade]
=> ["dog", "door", "rod", "blade"]
irb(main):048:0> words.all?(/o/)
=> false
irb(main):049:0> words.my_all?(/o/)
=> true
irb(main):050:0>
```

2019-11-07 10:03 UTC, maelfosso commented on module.rb
> +  end
```ruby
irb(main):051:0> array
=> [6, 7, 6, 4, 4, 2, 5, 1, 2, 5, 2, 3, 7, 6, 0, 3, 7, 0, 3, 1, 3, 4, 5, 3, 7, 8, 8, 5, 5, 5, 8, 1, 1, 0, 6, 4, 3, 7, 7, 4, 0, 0, 0, 1, 2, 7, 0, 8, 2, 8, 5, 1, 3, 5, 7, 6, 2, 1, 6, 2, 1, 5, 2, 5, 4, 0, 3, 4, 0, 2, 3, 6, 7, 0, 3, 5, 0, 6, 6, 3, 8, 3, 4, 2, 7, 7, 8, 7, 7, 5, 8, 1, 8, 1, 5, 2, 2, 1, 0, 5]
irb(main):052:0> array.all?(3)
=> false
irb(main):053:0> array.my_all?(3)
=> true
```

2019-11-07 10:03 UTC, maelfosso commented on module.rb
> +  end
```ruby
irb(main):056:0> true_array = [nil, false, true, []]
=> [nil, false, true, []]
irb(main):057:0> true_array.any?
=> true
irb(main):058:0> true_array.my_any?
=> false
```

2019-11-07 10:03 UTC, maelfosso commented on module.rb
> +  end
```ruby
irb(main):063:0> words
=> ["dog", "door", "rod", "blade"]
irb(main):064:0> words.any?('dog')
=> true
irb(main):065:0> words.my_any?('dog')
=> true
irb(main):066:0> words.any?('cat')
=> false
irb(main):067:0> words.my_any?('cat')
=> true
irb(main):068:0>
```

2019-11-07 10:03 UTC, maelfosso commented on module.rb
> +  end
```ruby
irb(main):070:0> true_block = proc { |num| num > 9 }
=> #<Proc:0x000055a97f2e2ba0@(irb):70>
irb(main):071:0> array.none?(&true_block)
=> true
irb(main):072:0> array.my_none?(&true_block)
=> false
```

2019-11-07 10:03 UTC, maelfosso commented on module.rb
> +  end
```ruby
irb(main):075:0> false_array = [nil, false, nil, false]
=> [nil, false, nil, false]
irb(main):076:0> false_array.none?
=> true
irb(main):077:0> false_array.my_none?
=> nil
```

2019-11-07 10:03 UTC, maelfosso commented on module.rb
> +  end
```ruby
irb(main):079:0> array
=> [6, 7, 6, 4, 4, 2, 5, 1, 2, 5, 2, 3, 7, 6, 0, 3, 7, 0, 3, 1, 3, 4, 5, 3, 7, 8, 8, 5, 5, 5, 8, 1, 1, 0, 6, 4, 3, 7, 7, 4, 0, 0, 0, 1, 2, 7, 0, 8, 2, 8, 5, 1, 3, 5, 7, 6, 2, 1, 6, 2, 1, 5, 2, 5, 4, 0, 3, 4, 0, 2, 3, 6, 7, 0, 3, 5, 0, 6, 6, 3, 8, 3, 4, 2, 7, 7, 8, 7, 7, 5, 8, 1, 8, 1, 5, 2, 2, 1, 0, 5]
irb(main):080:0> array.none?
=> false
irb(main):081:0> array.my_none?
=> nil
```

2019-11-07 10:03 UTC, maelfosso commented on module.rb
> +  end
```ruby
irb(main):084:0> words
=> ["dog", "door", "rod", "blade"]
irb(main):085:0> words.none?(/z/)
=> true
irb(main):086:0> words.my_none?(/z/)
=> false
```

2019-11-07 10:03 UTC, maelfosso commented on module.rb
> +  end
```ruby
irb(main):090:0> words
=> ["dog", "door", "rod", "blade"]
irb(main):091:0> words.none?(5)
=> true
irb(main):092:0> words.my_none?(5)
=> nil
```

2019-11-07 10:03 UTC, maelfosso commented on module.rb
> +  end
```ruby
irb(main):095:0> array
=> [6, 7, 6, 4, 4, 2, 5, 1, 2, 5, 2, 3, 7, 6, 0, 3, 7, 0, 3, 1, 3, 4, 5, 3, 7, 8, 8, 5, 5, 5, 8, 1, 1, 0, 6, 4, 3, 7, 7, 4, 0, 0, 0, 1, 2, 7, 0, 8, 2, 8, 5, 1, 3, 5, 7, 6, 2, 1, 6, 2, 1, 5, 2, 5, 4, 0, 3, 4, 0, 2, 3, 6, 7, 0, 3, 5, 0, 6, 6, 3, 8, 3, 4, 2, 7, 7, 8, 7, 7, 5, 8, 1, 8, 1, 5, 2, 2, 1, 0, 5]
irb(main):096:0> array.count(0)
=> 12
irb(main):097:0> array.my_count(0)
=> 100
```

2019-11-07 10:03 UTC, maelfosso commented on module.rb
> +end
```ruby
irb(main):101:0> range = Range.new(5, 50)
=> 5..50
irb(main):102:0> range.inject(4) { |prod, n| prod * n }
=> 5069015533618896340602101361010794807396273594826752000000000000
irb(main):103:0> range.my_inject(4) { |prod, n| prod * n }
Traceback (most recent call last):
        3: from /home/elvisfosso/.rbenv/versions/2.5.1/bin/irb:11:in `<main>'
        2: from (irb):103
        1: from module.rb:82:in `my_inject'
NoMethodError (undefined method `[]' for 5..50:Range)
irb(main):104:0>
```

2019-11-07 10:03 UTC, maelfosso commented on module.rb
> +end
```ruby
irb(main):106:0> range.inject(2, :*)
=> 2534507766809448170301050680505397403698136797413376000000000000
irb(main):107:0> range.my_inject(2, :*)
Traceback (most recent call last):
        6: from /home/elvisfosso/.rbenv/versions/2.5.1/bin/irb:11:in `<main>'
        5: from (irb):107
        4: from module.rb:75:in `my_inject'
        3: from module.rb:5:in `my_each'
        2: from module.rb:5:in `each'
        1: from module.rb:6:in `block in my_each'
NoMethodError (undefined method `[]' for 5..50:Range)
irb(main):108:0>
```

2019-11-25 15:16 UTC, wickathou commented on module.rb
> +  end
my_each_with_index fixed

2019-11-27 01:19 UTC, Forison requested changes
Hi @wickathou🙂,
You have done a good job so far.🙂
Your project is not following the desired git-flow for this project. Git-flows are mandatory requirements that ought to be obeyed by all students in every project.
Your PR must be made from the feature branch to the development branch.
#### Kindly do these change and make sure all your custom methods behave as they should🙂.
#### Happy coding🙂
@forison

2019-11-27 15:22 UTC, wickathou commented
> Hi @wickathou🙂,
> You have done a good job so far.🙂
> Your project is not following the desired git-flow for this project. Git-flows are mandatory requirements that ought to be obeyed by all students in every project.
> Your PR must be made from the feature branch to the development branch.
> 
> #### Kindly do these change and make sure all your custom methods behave as they should🙂.
> #### Happy coding🙂
> @Forison

Done

2019-11-27 17:20 UTC, whiz25 requested changes
## Nice try @wickathou :+1: 
You have implemented the suggested changes, that' good. You still have some edge cases that are missing and for that we need to do some work before we can move on.
Check out my comments and try your level best to implement them and send for another review.

### Martin Afani

2019-11-27 17:27 UTC, whiz25 commented on module.rb
> +  end
- [ ] when a class is passed as an argument returns true if all of the collection is a member of such class
- [ ] when a Regex is passed as an argument returns true if all of the collection matches the Regex
- [ ] when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

2019-11-27 17:28 UTC, whiz25 commented on module.rb
> +  end
- [ ] when a class is passed as an argument returns true if at least one of the collection is a member of such class
- [ ] when a Regex is passed as an argument returns false if none of the collection matches the Regex
- [ ] when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern

2019-11-27 17:28 UTC, whiz25 commented on module.rb
>      end
- [ ] when a Regex is passed as an argument returns true only if none of the collection matches the Regex
- [ ] when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern

2019-11-27 17:29 UTC, whiz25 commented on module.rb
> +  end
- [ ] returns the number of items in enum through enumeration
- [ ] counts the number of items in enum that are equal to item if an argument is given
- [ ] counts the number of elements yielding a true value if a block is given

2019-11-27 17:30 UTC, whiz25 commented on module.rb
> +  end
- [ ] combines all elements of enum by applying a binary operation, specified by a block

2019-11-27 17:51 UTC, wickathou commented on module.rb
> +  end
I'm confused, because I re-tested everything and it works as expected. Could you show where are this failures you described?

2019-11-27 18:07 UTC, wathigo requested changes
# Changes Required  
## Great progress so far :clap: 
Let's fix a few issues pointed out in the comments :point_down:. Error messages have been included for easier debugging.

### After implementing the changes, submit another request for review.

**Happy Coding :computer: 
Simon Wathigo**

2019-11-27 18:07 UTC, wathigo commented on module.rb
> +  end
**[REQUIRED]**
* Returns the number of items in enum through enumeration.
```
Failure/Error: expect(array.my_count).to eq array.count
     
     NameError:
       undefined local variable or method `a' for #<Array:0x00005632f189d8f0>
       Did you mean?  at
```
* Counts the number of items in enum that are equal to item if an argument is given.
```
Failure/Error: expect(array.my_count(LOWEST_VALUE)).to eq array.count(LOWEST_VALUE)
     
     NameError:
       undefined local variable or method `a' for #<Array:0x00005632f18a6040>
       Did you mean?  at
```
* Counts the number of elements yielding a true value if a block is given.
```
Failure/Error: expect(array.my_count(&block)).to eq array.count(&block)
     
     NameError:
       undefined local variable or method `a' for #<Array:0x00005632f18b13f0>
       Did you mean?  a
```

2019-11-27 18:07 UTC, wathigo commented on module.rb
> +  end
**[REQUIRED]**
* Combines all elements of enum by applying a binary operation, specified by a block.
```
Failure/Error: let(:search) { proc { |memo, word| memo.length > word.length ? memo : word } }
     
     NoMethodError:
       undefined method `length' for 0:Integer
```

2019-11-27 18:27 UTC, wickathou commented on module.rb
> +  end
Fixed.

2019-11-27 20:16 UTC, whiz25 approved these changes
## Hey @wickathou 
You still have alot of edge cases failing in your methods but since this review has surpassed the max number of cycles, I am giving you the :+1: . Please go and merge.
#### You can try to cover the failing edge cases of the ```my_any```, ```my_all```, ```my_none``` and ```my_inject``` methods for your learning purpose.

### Martin Afani

2019-11-27 22:32 UTC, merged